[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4==4.12.3",
    "discord-webhook==1.3.1",
    "playwright==1.49.0",
    "requests==2.32.3",
]
